#!/usr/bin/python

mongodbmetrics_ServerStatus=[
	{
		'param' : ['asserts','msg'],
		'name' : 'asserts.msg',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().asserts.msg)"| awk "NR>=3 {print}"',
		'description' : 'Number of message assertions raised during the selected time period',
		'type' : 'summary'		
	},

	{
		'param' : ['asserts','warning'],
		'name' : 'asserts.warning',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().asserts.warning)"| awk "NR>=3 {print}"',
		'description' : 'Number of warning assertions raised during the selected time period',
		'type' : 'summary'		
	},

	{
		'param' : ['asserts','regular'],
		'name' : 'asserts.regular',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().asserts.regular)"| awk "NR>=3 {print}"',
		'description' : 'Number of regular assertions raised during the selected time period',
		'type' : 'summary'
	},

	{
		'param' : ['asserts','user'],
		'name' : 'asserts.user',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().asserts.user)"| awk "NR>=3 {print}"',
		'description' : 'Number of assertions corresponding to errors generated by users during the selected time period',
		'type' : 'summary'
	},

	{
		'param' : ['globalLock','currentQueue','readers'],
		'name' : 'globalLock.currentQueue.',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().globalLock.currentQueue.readers)"| awk "NR>=3 {print}"',
		'description' : 'Number of read requests currently queued',
		'type' : 'summary'
	},

	{
		'param' : ['globalLock','currentQueue','writers'],
		'name' : 'globalLock.currentQueue.writers',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().globalLock.currentQueue.writers)"| awk "NR>=3 {print}"',
		'description' : 'Number of write requests currently queued',
		'type' : 'summary'
	},

	{
		'param' : ['wiredTiger','cache','bytes currently in the cache'],
		'name' : 'wiredTiger.cache.bytes currently in the cache',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().wiredTiger.cache.bytes currently in the cache)"| awk "NR>=3 {print}"',
		'description' : 'Amount of space taken by cached data (bytes)',
		'type' : 'summary'
	},

	{
		'param' : ['wiredTiger','cache','maximum bytes configured'],
		'name' : 'wiredTiger.cache.maximum bytes configured',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().wiredTiger.cache.maximum bytes configured)"| awk "NR>=3 {print}"',
		'description' : 'Maximum cache size configured (bytes)',
		'type' : 'summary'
	},

	{
		'param' : ['wiredTiger','cache','tracked dirty bytes in the cache'],
		'name' : 'wiredTiger.cache.tracked dirty bytes in the cache',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().wiredTiger.cache.tracked dirty bytes in the cache)"| awk "NR>{print}"',
		'description' : 'Amount of space taken by dirty data in the cache (bytes)',
		'type' : 'summary'
	},

	{
		'param' : ['wiredTiger','cache','unmodified pages evicted'],
		'name' : 'wiredTiger.cache.unmodified pages evicted',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().wiredTiger.cache.unmodified pages evicted)"| awk "NR>=3 {print}"',
		'description' : 'Number of pages unmodified evicted from the cache',
		'type' : 'summary'
	},

	{
		'param' : ['wiredTiger','cache','modified pages evicted'],
		'name' : 'wiredTiger.cache.wiredTiger.cache.modified pages evicted',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().wiredTiger.cache.modified pages evicted)"| awk "NR>=3 {print}"',
		'description' : 'Number of pages modified evicted from the cache',
		'type' : 'summary'
	},

	{
		'param' : ['mem','virtual'],
		'name' : 'mem.virtual',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().mem.virtual)"| awk "NR>=3 {print}"',
		'description' : 'Virtual memory usage (MB)',
		'type' : 'summary'
	},

	{
		'param' : ['mem','resident'],
		'name' : 'mem.resident',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().mem.resident)"| awk "NR>=3 {print}"',
		'description' : 'Amount of memory used by the database process (MB)',
		'type' : 'summary'
	},

	{
		'param' : ['extra_info','page_faults'],
		'name' : 'extra_info.page_faults',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().extra_info.page_faults)"| awk "NR>=3 {print}"',
		'description' : 'Number of times MongoDB had to request from disk (per second)',
		'type' : 'summary'
	},

	{
		'param' : ['connections','current'],
		'name' : 'connections.current',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().connections.current)"| awk "NR>=3 {print}"',
		'description' : 'Number of clients currently connected to the database server',
		'type' : 'summary'
	},

	{
		'param' : ['connections','available'],
		'name' : 'connections.available',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().connections.available)"| awk "NR>=3 {print}"',
		'description' : 'Number of unused connections available for new clients',
		'type' : 'summary'
	},

	{
		'param' : ['metrics','cursor','open','total'],
		'name' : 'metrics.cursor.open.total',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().metrics.cursor.open.total)"| awk "NR>=3 {print}"',
		'description' : 'Number of cursors currently opened by MongoDB for clients',
		'type' : 'summary'
	},

	{
		'param' : ['metrics','cursor','timedOut'],
		'name' : 'metrics.cursor.timedOut',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().metrics.cursor.timedOut)"| awk "NR>=3 {print}"',
		'description' : 'Number of cursors that have timed out during the selected time period',
		'type' : 'summary'
	},

	{
		'param' : ['metrics','cursor','open','noTimeout'],
		'name' : 'metrics.cursor.open.noTimeout',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().metrics.cursor.open.noTimeout)"| awk "NR>=3 {print}"',
		'description' : 'The number of open cursors with timeout disabled',
		'type' : 'summary'
	},

	{
		'param' : ['wiredTiger','concurrentTransactions','read','out'],
		'name' : 'wiredTiger.concurrentTransactions.read.out',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().wiredTiger.concurrentTransactions.read.out)"| awk "NR>=3 {print}"',
		'description' : 'Number of read tickets in use',
		'type' : 'summary'
	},


	{
		'param' : ['wiredTiger','concurrentTransactions','write','out'],
		'name' : 'wiredTiger.concurrentTransactions.write.out',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().wiredTiger.concurrentTransactions.write.out)"| awk "NR>=3 {print}"',
		'description' : 'Number of write tickets in use',
		'type' : 'summary'
	},

	{
		'param' : ['wiredTiger','concurrentTransactions','read','available'],
		'name' : 'wiredTiger.concurrentTransactions.read.available',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().wiredTiger.concurrentTransactions.read.available)"| awk "NR>=3 {print}"',
		'description' : 'Number of available read tickets remaining',
		'type' : 'summary'
	},

	{
		'param' : ['wiredTiger','concurrentTransactions','write','available'],
		'name' : 'wiredTiger.concurrentTransactions.write.available',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().wiredTiger.concurrentTransactions.write.available)"| awk "NR>=3 {print}"',
		'description' : 'Number of available write tickets remaining',
		'type' : 'summary'
	},

	{
		'param' : ['globalLock','activeClients','writers'],
		'name' : 'globalLock.activeClients.writers',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().globalLock.activeClients.writers)"| awk "NR>=3 {print}"',
		'description' : 'Number of clients with write operations in progress or queued',
		'type' : 'summary'
	},

	{
		'param' : ['globalLock','activeClients','readers'],
		'name' : 'globalLock.activeClients.readers',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().globalLock.activeClients.readers)"| awk "NR>=3 {print}"',
		'description' : 'Number of clients with read operations in progress or queued',
		'type' : 'summary'
	},

	{
		'param' : ['opcounters','delete'],
		'name' : 'opcounters.delete',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().opcounters.delete)"| awk "NR>=3 {print}"',
		'description' : 'Number of write requests received during the selected time period (delete)',
		'type' : 'summary'
	},

	{
		'param' : ['opcounters','update',],
		'name' : 'opcounters.update',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().opcounters.update)"| awk "NR>=3 {print}"',
		'description' : 'Number of write requests received during the selected time period (update)',
		'type' : 'summary'
	},

	{
		'param' : ['opcounters','insert',],
		'name' : 'opcounters.insert',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().opcounters.insert)"| awk "NR>=3 {print}"',
		'description' : 'Number of write requests received during the selected time period (insert)',
		'type' : 'summary'
	},

	{
		'param' : ['opcounters','query',],
		'name' : 'opcounters.query',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().opcounters.query)"| awk "NR>=3 {print}"',
		'description' : 'Number of read requests received during the selected time period (query)',
		'type' : 'summary'
	},
		
	{
		'param' : ['opcounters','getmore',],
		'name' : 'opcounters.getmore',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.serverStatus().opcounters.getmore)"| awk "NR>=3 {print}"',
		'description' : 'Number of read requests received during the selected time period (getmore)',
		'type' : 'summary'
	},



	
]

mongodbmetrics_dbstats=[

	{
		'param' : ['objects'],
		'name' : 'objects',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.stats().objects)"| awk "NR>=3 {print}"',
		'description' : 'Number of objects (documents) among all the collections',
		'type' : 'summary'
	},
		
	{
		'param' : ['dataSize'],
		'name' : 'dataSize',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.stats().dataSize)"| awk "NR>=3 {print}"',
		'description' : 'Size of all documents (bytes)',
		'type' : 'summary'
	},

	{
		'param' : ['indexSize'],
		'name' : 'indexSize',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.stats().indexSize)"| awk "NR>=3 {print}"',
		'description' : 'Size of all indexes (bytes)',
		'type' : 'summary'
	},

	{
		'param' : ['storageSize'],
		'name' : 'storageSize',
		'datatype' : 'float',
		'command' : 'mongo dbname --eval "printjson(db.stats().storageSize)"| awk "NR>=3 {print}"',
		'description' : 'Size of all extents (bytes)',
		'type' : 'summary'
	},


]
